export const userConstants = {
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE",

  LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USERS_LOGIN_FAILURE",

  FORGOTPASSWORD: "USERS_FORGOTPASSWORD",

  LOGOUT: "USERS_LOGOUT",

  GETALL_REQUEST: "USERS_GETALL_REQUEST",
  GETALL_SUCCESS: "USERS_GETALL_SUCCESS",
  GETALL_FAILURE: "USERS_GETALL_FAILURE",

  GETBYID_REQUEST: "USER_GETBYID_REQUEST",
  GETBYID_SUCCESS: "USER_GETBYID_SUCCESS",
  GETBYID_FAILURE: "USER_GETBYID_FAILURE",

  NEWUSER_REQUEST: "USER_NEWUSER_REQUEST",
  NEWUSER_SUCCESS: "USER_NEWUSER_SUCCESS",
  NEWUSER_FAILURE: "USER_NEWUSER_FAILURE",

  DELETE_REQUEST: "USERS_DELETE_REQUEST",
  DELETE_SUCCESS: "USERS_DELETE_SUCCESS",
  DELETE_FAILURE: "USERS_DELETE_FAILURE",

  UPDATEADMIN_REQUEST: "USERS_UPDATEADMIN_REQUEST",
  UPDATEADMIN_SUCCESS: "USERS_UPDATEADMIN_SUCCESS",
  UPDATEADMIN_FAILURE: "USERS_UPDATEADMIN_FAILURE",

  SHOW_LOADING: "SHOW_LOADING",
};
